In [90]:
import metaflow
from metaflow import Flow, Task, Metaflow, Run, project

---

In [27]:
mf = Metaflow()

In [28]:
print(Metaflow().flows)

[Flow('RecommendationsFlow'), Flow('MovielensALSFlow')]

In [119]:
flow = Flow('MovielensALSFlow')

for run in list(flow):
    print(run)

Run('MovielensALSFlow/17')
Run('MovielensALSFlow/16')
Run('MovielensALSFlow/15')
Run('MovielensALSFlow/14')
Run('MovielensALSFlow/13')
Run('MovielensALSFlow/12')
Run('MovielensALSFlow/11')

---

In [120]:
run_id = '16'
task_id = '106'

In [121]:
ratings = Task(f'MovielensALSFlow/{run_id}/train/{task_id}', attempt=0)['ratings'].data

In [122]:
model = Task(f'MovielensALSFlow/{run_id}/train/{task_id}', attempt=0)['model'].data

---

In [123]:
movies_mapping = ratings[['itemID', 'title', 'genre']].drop_duplicates().set_index('itemID')

In [124]:
def _similar_wrapper(item_id, N=10, model=model):
    return movies_mapping.loc[
        list(model.similar_items(item_id, N=N)[0])
    ]

In [125]:
_similar_wrapper(1, N=20)

,title,genre
itemID,,
1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
156,Blue in the Face (1995),Comedy|Drama
580,Princess Caraboo (1994),Drama
363,"Wonderful, Horrible Life of Leni Riefenstahl, ...",Documentary
314,"Secret of Roan Inish, The (1994)",Children|Drama|Fantasy|Mystery
360,I Love Trouble (1994),Action|Comedy
496,What Happened Was... (1994),Comedy|Drama|Romance
206,Unzipped (1995),Documentary
581,"Celluloid Closet, The (1995)",Documentary
158,Casper (1995),Adventure|Children
47,Seven (a.k.a. Se7en) (1995),Crime|Horror|Mystery|Thriller
431,Carlito's Way (1993),Crime|Drama
183,Mute Witness (1994),Comedy|Horror|Thriller
151,Rob Roy (1995),Action|Drama|Romance|War
406,Federal Hill (1994),Drama
18,Four Rooms (1995),Comedy|Drama|Thriller
438,"Cowboy Way, The (1994)",Action|Comedy|Drama
589,Terminator 2: Judgment Day (1991),Action|Sci-Fi
582,MÃ©tisse (CafÃ© au Lait) (1993),Comedy|Drama
166,"Doom Generation, The (1995)",Comedy|Crime|Drama

In [111]:
movies_mapping.sort_index().head(50)

,title,genre
itemID,,
1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
2,Jumanji (1995),Adventure|Children|Fantasy
3,Grumpier Old Men (1995),Comedy|Romance
4,Waiting to Exhale (1995),Comedy|Drama|Romance
5,Father of the Bride Part II (1995),Comedy
6,Heat (1995),Action|Crime|Thriller
7,Sabrina (1995),Comedy|Romance
8,Tom and Huck (1995),Adventure|Children
9,Sudden Death (1995),Action
10,GoldenEye (1995),Action|Adventure|Thriller
11,"American President, The (1995)",Comedy|Drama|Romance
12,Dracula: Dead and Loving It (1995),Comedy|Horror
13,Balto (1995),Animation|Children
14,Nixon (1995),Drama
15,Cutthroat Island (1995),Action|Adventure|Romance
16,Casino (1995),Crime|Drama
17,Sense and Sensibility (1995),Comedy|Drama|Romance
18,Four Rooms (1995),Comedy|Drama|Thriller
19,Ace Ventura: When Nature Calls (1995),Comedy
20,Money Train (1995),Action|Comedy|Crime|Drama|Thriller
21,Get Shorty (1995),Action|Comedy|Drama
22,Copycat (1995),Crime|Drama|Horror|Mystery|Thriller
23,Assassins (1995),Action|Crime|Thriller
24,Powder (1995),Drama|Sci-Fi
25,Leaving Las Vegas (1995),Drama|Romance
26,Othello (1995),Drama
27,Now and Then (1995),Drama
28,Persuasion (1995),Drama|Romance
29,"City of Lost Children, The (CitÃ© des enfants ...",Adventure|Drama|Fantasy|Mystery|Sci-Fi
30,Shanghai Triad (Yao a yao yao dao waipo qiao) ...,Crime|Drama
31,Dangerous Minds (1995),Drama
32,12 Monkeys (Twelve Monkeys) (1995),Sci-Fi|Thriller
33,Wings of Courage (1995),Adventure|IMAX|Romance
34,Babe (1995),Children|Comedy|Drama|Fantasy
35,Carrington (1995),Drama|Romance
36,Dead Man Walking (1995),Crime|Drama
37,Across the Sea of Time (1995),Documentary|IMAX
38,It Takes Two (1995),Comedy
39,Clueless (1995),Comedy|Romance
40,"Cry, the Beloved Country (1995)",Drama
41,Richard III (1995),Drama|War
42,Dead Presidents (1995),Action|Crime|Drama
43,Restoration (1995),Drama
44,Mortal Kombat (1995),Action|Adventure|Fantasy
45,To Die For (1995),Comedy|Drama|Thriller
46,How to Make an American Quilt (1995),Drama|Romance
47,Seven (a.k.a. Se7en) (1995),Crime|Horror|Mystery|Thriller
48,Pocahontas (1995),Animation|Children|Musical|Romance
49,When Night Is Falling (1995),Drama|Romance
50,"Usual Suspects, The (1995)",Crime|Mystery|Thriller

In [118]:
ratings.groupby('itemID').agg(
    {'rating': ['mean', 'sum']}
)

          rating
            mean       sum
itemID
1       3.928769  103912.0
2       3.208070   38599.5
3       3.150385   24541.5
4       2.860544    5046.0
5       3.077435   21957.5
...          ...       ...
65088   3.062500      24.5
65091   3.666667      11.0
65126   3.666667      11.0
65130   2.250000       4.5
65133   3.357143      23.5

[10677 rows x 2 columns]